title: Shelter Four
description: An eclectic instrumental electronic/funk fusion band established in 2017.
url: https://shelterfour.net
logo: /assets/img/favicon.png

compress_html:
  comments: all

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock

kramdown:
  auto_ids: false
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
